const projects = [
  {
    id: 1,
    name: "Blog Publisher",
    about:
      "Zsans Blog Publisher, is a media provider of various articles, you can easily publish and write your articles, create your articles and achieve top trending!",
    tags: "#fullstack, #html, #css, #react, #big-project",
    category: "Big Project",
    live: "https://www.zsans-product.tech",
    github: "",
    image: "/zsans-blog-publisher-promo.png",
    languages: {
      html: "50%",
      css: "30%",
      javascript: "80%",
      reactjs: "90%",
      nodejs: "70%",
      database: "45%",
      tailwind: "70%",
      other: "40%",
    },
  },
  {
    id: 2,
    name: "Sans Blog",
    about:
      "Sans Blog is my personal blog, in which you can read and publish a blog with the image, tittle and content of your blog.",
    tags: "#javascript, #fullstack, #css, #html",
    category: "Fullstack",
    live: "https://personal-portofolio-mu.vercel.app/features/blogging-site/home.html",
    github: "",
    image: "/portofolio_blogpublisher.jpg",
    languages: {
      html: "80%",
      css: "80%",
      javascript: "70%",
      reactjs: "0%",
      nodejs: "0%",
      database: "0%",
      tailwind: "0%",
      other: "0%",
    },
  },
  {
    id: 3,
    name: "Sans Wiki",
    about:
      "Sans Wiki is a search engine using the wikipedia API, everything on wikipedia can be searched here.",
    tags: "#fullstack, #javascript, #css, #html",
    category: "Fullstack",
    live: "https://personal-portofolio-mu.vercel.app/features/wiki-site/wiki.html",
    github: "",
    image: "/zsans_wiki.jpg",
    languages: {
      html: "90%",
      css: "90%",
      javascript: "80%",
      reactjs: "0%",
      nodejs: "0%",
      database: "0%",
      tailwind: "0%",
      other: "0%",
    },
  },
  {
    id: 4,
    name: "Spotify Clone",
    about:
      "In this Spotify Clone, I cloned the front-end, the progress is only up to the home page and 50% responsive.",
    tags: "#frontend, #html, #css",
    category: "Frontend",
    live: "https://personal-portofolio-mu.vercel.app/features/spotify-clone/spoti-home.html",
    github: "",
    image: "/spotify_clone.jpg",
    languages: {
      html: "90%",
      css: "90%",
      javascript: "15%",
      reactjs: "0%",
      nodejs: "0%",
      database: "0%",
      tailwind: "0%",
      other: "0%",
    },
  },
  {
    id: 5,
    name: "Personal Portofolio V1",
    about: "Personal Portofolio V1.",
    tags: "#frontend, #html, #css, #javascript",
    category: "Frontend",
    live: "https://personal-portofolio-mu.vercel.app/",
    github: "",
    image: "/portofolioV1.jpg",
    languages: {
      html: "90%",
      css: "90%",
      javascript: "15%",
      reactjs: "0%",
      nodejs: "0%",
      database: "0%",
      tailwind: "0%",
      other: "0%",
    },
  },
  {
    id: 6,
    name: "Zsans Kanban",
    about: "Zsans Kanban is for personal project management",
    tags: "#fullstack, #taillwind, #javascript, #react",
    category: "Fullstack",
    live: "https://github.com/sandi-hermawan01/zsans-kanban",
    github: "",
    image: "/kanban_banner.jpg",
    languages: {
      html: "90%",
      css: "90%",
      javascript: "15%",
      reactjs: "0%",
      nodejs: "0%",
      database: "0%",
      tailwind: "0%",
      other: "0%",
    },
  },
];

export default projects;
